import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/globals.scss'
import Header from '@/Components/Header/page'
import { Locale } from '@/../i18n.config'
import { GlobalProvider } from '@/../lib/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Головна',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }: 
  { children: React.ReactNode, params: { locale: Locale }
}) {
  return (
    <html lang={params.locale}>
      <head>
        <link rel="icon" type="image/png" href="/favicon-tea-leaf.png" />
      </head>
      <body className={inter.className}>
        <GlobalProvider>
          <Header />
          {children}
        </GlobalProvider>
      </body>
    </html>
  )
}
